export const GET_FOLDERS = 'GET_FOLDERS';
export const SELECT_FOLDERS = 'SELECT_FOLDERS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_LANGUAGES = 'GET_LANGUAGES';
export const RENAME_FOLDER = 'RENAME_FOLDER';
