const BACK_END_PORT = 8000;
const BASE_API = `http://localhost:${BACK_END_PORT}`;

const MODULE = {
  FOLDER: '/folder',
  CATEGORY: '/category',
  LANGUAGE: '/language',
  TAG: '/tag'
};

const CONTROLLER_PATH = {
  GET: '/',
  MODIFY: '/modify',
  ADD: '/add',
  IMPORT: '/import',
  EXPORT: '/export'
};

const FOLDER_API = {
  GET: `${MODULE.FOLDER}${CONTROLLER_PATH.GET}`,
  ADD: `${MODULE.FOLDER}${CONTROLLER_PATH.ADD}`,
  IMPORT: `${MODULE.FOLDER}${CONTROLLER_PATH.IMPORT}`,
  EXPORT: `${MODULE.FOLDER}${CONTROLLER_PATH.EXPORT}`
};

const CATEGORY_API = {
  GET: `${MODULE.CATEGORY}${CONTROLLER_PATH.GET}`
};

const LANGUAGE_API = {
  GET: `${MODULE.LANGUAGE}${CONTROLLER_PATH.GET}`
};

const TAG_API = {
  GET: `${MODULE.TAG}${CONTROLLER_PATH.GET}`,
  MODIFY: `${MODULE.TAG}${CONTROLLER_PATH.MODIFY}`
};

export {
  BACK_END_PORT,
  BASE_API,
  MODULE,
  CONTROLLER_PATH,
  FOLDER_API,
  CATEGORY_API,
  LANGUAGE_API,
  TAG_API
};
