const DATABASE_DIRECTORY = 'Database';
const DATABASE_NAME = 'test.db';
const DATABASE_PATH = `${DATABASE_DIRECTORY}/${DATABASE_NAME}`;

const DATABASE = {
  DIRECTORY: DATABASE_DIRECTORY,
  NAME: DATABASE_NAME,
  PATH: DATABASE_PATH
};

export default DATABASE;
