export const GET_TAGS = 'GET_TAGS';
export const LOAD_TAG_RELATIONS = 'LOAD_TAG_RELATIONS';
export const COPY_TAGS = 'COPY_TAGS';
export const CLEAR_CLIPBOARD = 'CLEAR_CLIPBOARD';
export const GET_MANAGED_TAGS = 'GET_MANAGED_TAGS';
