enum IPC_EVENT {
  ADD_FOLDERS = 'ADD_FOLDERS',
  OPEN_SETTING = 'OPEN_SETTING',
  IMPORT_DATA = 'IMPORT_DATA',
  EXPORT_DATA = 'EXPORT_DATA',
  CALCULATE_TAGS_RELATION = 'CALCULATE_TAGS_RELATION'
}

export default IPC_EVENT;
